ko_fi: chaosesib
custom: [
  "https://ifdian.net/a/Chaoses-Ib",
  "https://chaoses-ib.github.io/微信赞赏码.png",
  "https://chaoses-ib.github.io/支付宝收款码.png",
  "Thanks_for_donation.Please_include_project_name.感谢捐赠，请备注项目名"
]
